Return kids-mobile as application code for old app versions
bcc-code/bcc-media-platform pull request #1014
Opened 2024-09-27 13:17 UTC by mulundapm

2024-09-27 17:51 UTC, kkuepper commented on backend/applications/middleware.go
> +// Support app version with old application name kids
In general it's better to only comment why you're doing something and not the what.
For the What it's better to refactor the code and make it easier to understand.

2024-09-27 17:51 UTC, kkuepper approved these changes

2024-09-28 13:20 UTC, andreasgangso requested changes

2024-09-30 11:43 UTC, kkuepper approved these changes

2024-09-30 15:36 UTC, merged