TimedMetadata
bcc-code/bcc-media-platform pull request #488
Opened 2023-08-31 08:10 UTC by fredrikved

This is the 2nd PR addressing chapters and names/titles for the chapters, making them "type"-safe.

Also implementing "phrases", so we can store and retrieve translations for specific key/values.

2023-08-31 08:29 UTC, andreasgangso requested changes

2023-08-31 08:29 UTC, andreasgangso commented on backend/graph/api/episodes.resolvers.go
> +					break
Maybe not exclude it if the song is invalid. E.g. "andre sanger". Chapter type can still be song but it just doesn't have a number

2023-08-31 08:29 UTC, andreasgangso commented on backend/graph/api/episodes.resolvers.go
> +				if person == nil {
Same, if person is null, but title is not null, use title instead of excluding?

2023-08-31 12:27 UTC, andreasgangso submitted a review, later dismissed
lgtm, but only did a rough logic review

2023-08-31 12:27 UTC, andreasgangso commented on backend/graph/api/episodes.resolvers.go
> +				title += " - " + song.Title.Get(languages)
I'd prefer being explicit wherever title is set, instead of appending

2023-09-05 13:30 UTC, KillerX submitted a review, later dismissed

2023-09-06 06:55 UTC, merged